version: '3.8'

services:
  web:
    build: ./fly
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./fly/:/usr/src/fly/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
      - POSTGRES_DB=test

volumes:
  postgres_data: